version: '3.10'

services:
  fastapi-app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    volumes:
      - ./app/images:/app/images
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    env_file:
      - ./app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: