version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FACE_CLOUD_API_URL=${FACE_CLOUD_API_URL}
      - FACE_CLOUD_LOGIN=${FACE_CLOUD_LOGIN}
      - FACE_CLOUD_PASSWORD=${FACE_CLOUD_PASSWORD}
    volumes:
      - .:/app
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
